{
 "title": "F*** you ISP!",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Common Services (<100ms is good for audio/video calls)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (name) (ping_rtt_seconds{type=\"mean\", name!~\"AWS.*|DevTunnel.*|Hetzner.*|Linode.*|GCP.*|OCI.*|Digital.*|Exoscale.*|OVH.*|Vultr.*|.*-dns|dev-.*\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "DNS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (name) (ping_rtt_seconds{type=\"mean\", name=~\".*-dns\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "DevTunnels",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (name) (ping_rtt_seconds{type=\"mean\", name=~\"DevTunnel.*\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Hetzner",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (name) (ping_rtt_seconds{type=\"mean\", name=~\"Hetzner.*\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Amazon Web Services",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (name) (ping_rtt_seconds{type=\"mean\", name=~\"AWS.*\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Google Cloud Platform",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (name) (ping_rtt_seconds{type=\"mean\", name=~\"GCP.*\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Various Dev Related Services",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (name) (ping_rtt_seconds{type=\"mean\", name=~\"dev.*\"})",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}